# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Calculate Fst using the model 
#' @param results - the output of \code{\link{sample.bayesFst}}
#' @return a matrix with \code{nout} rows and \code{nloci * npop} columns
#' @export
CalcFst <- function(results) {
    .Call('_rbayesfst_CalcFst', PACKAGE = 'rbayesfst', results)
}

